# Importa a senha do seu .env
spring.config.import=optional:file:.env[.properties]

spring.application.name=backend

# CONEXÃO COM O BANCO DE DADOS
spring.datasource.url=jdbc:postgresql://localhost:5432/logistica
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Limites de upload de arquivos (manifestos)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
